CREATE TABLE users (
  id SERIAL4 PRIMARY KEY,
  email VARCHAR(254) NOT NULL,
  password_digest VARCHAR(400) NOT NULL,
  full_name VARCHAR(255),
  deleted BOOLEAN NOT NULL
);

CREATE TABLE albums (
  id SERIAL4 PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  user_id INTEGER NOT NULL,
  deleted BOOLEAN NOT NULL
);

CREATE TABLE photos (
  id SERIAL4 PRIMARY KEY,
  url VARCHAR(400) NOT NULL,
  album_id INTEGER NOT NULL,
  deleted BOOLEAN NOT NULL
);
